package:
  name: adaptivemd-dev
  version: "0.2.0"

source:
#  git_url: ../../.git
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - pymongo>=3.4
    - numpy
    - ujson
    - six
    - jsonschema
    #- radical.utils
    #- saga-python
    #- radical.pilot

  run:
    - python
    - pymongo>=3.4
    - numpy
    - ujson
    #- radical.utils
    #- saga-python
    #- radical.pilot

test:
  requires:
    - pytest
    - nbval
    - pyemma
    - openmm

  imports:
    - adaptivemd

  source_files:
    - examples/*

  commands:
    #- pip install radical.utils
    #- pip install saga-python
    - pip install radical.pilot
    - pip install pytest-timeout
    - py.test -v --pyargs adaptivemd --doctest-modules --timeout=500
    #- py.test -v --nbval examples/

about:
  home: https://github.com/markovmodel/adaptivemd
  license: LGPL 2.1 or later
  summary: 'A framework to run Molecular Dynamics Simulations in Adaptive Sampling Workflows.'
   
